#!/usr/bin/env bash
# Generate bin/ wrappers for the release bundle so the binaries can go on PATH.
#
# Every binary in build/ carries a RUNPATH pointing at the machine it was compiled on, so run by
# absolute path it can silently load the wrong libggml-cuda.so. Each wrapper sets LD_LIBRARY_PATH
# to its own bundle first, then execs. That is the whole reason this directory exists.
#
# Called by sync.sh. Usage: ./make-wrappers.sh [/mnt/fast/p100-llamacpp-release]
set -euo pipefail

REL="${1:-/mnt/fast/p100-llamacpp-release}"
BIN="$REL/bin"
[ -d "$REL/build" ] || { echo "no build/ in $REL"; exit 1; }

rm -rf "$BIN"
mkdir -p "$BIN"

n=0
for exe in "$REL"/build/*; do
    name="$(basename "$exe")"
    case "$name" in *.so|*.so.*|*.a|*.cmake|*.h) continue ;; esac
    [ -f "$exe" ] && [ -x "$exe" ] || continue
    cat > "$BIN/$name" <<EOF
#!/bin/sh
# Generated by release-sync/make-wrappers.sh -- do not edit; regenerate instead.
BUILD="\$(cd "\$(dirname "\$0")/../build" && pwd)"
LD_LIBRARY_PATH="\$BUILD\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}" export LD_LIBRARY_PATH
exec "\$BUILD/$name" "\$@"
EOF
    chmod +x "$BIN/$name"
    n=$((n+1))
done

# The tuned serving configuration as a single command. Anything passed on the command line is
# appended, and llama.cpp takes the last occurrence of a flag, so `qwen-server --port 9000`
# overrides the port below without editing this file.
cat > "$BIN/qwen-server" <<'EOF'
#!/bin/sh
# Generated by release-sync/make-wrappers.sh -- do not edit; regenerate instead.
#
# The tuned long-context + MTP serving configuration for 2x P100. See docs/QUICKSTART.md for
# what each flag does and why. Extra arguments are appended and win over the defaults here.
#
# Sized for VRAM margin, not for peak shallow prefill. The attention mask is n_kv x ubatch and
# n_kv is the USED cache, so the footprint grows as the context fills -- steeply at the very end.
# ubatch only costs real VRAM when CUDA graphs are ON, which they are not here. With graphs on
# the scaling was 10.67 MiB per ubatch unit at full depth and -ub 512 got killed at 193 MiB free;
# with graphs off it is 0.84 MiB per unit, which is just the f16 mask over the target and draft
# contexts. Measured at full depth, single-shot, MTP on, graphs off:
#     ub    prefill      decode     acceptance   min gpu0 free
#     256  119.46 t/s  26.13 t/s     0.98058       2205 MiB
#     2048 137.43 t/s  25.53 t/s     0.98058        757 MiB
# +15% prefill for identical acceptance and decode. The margin is the thing to watch: 757 MiB is
# 3.8x the watchdog floor, but run163 died from a 136 MiB swing in other GPU use. If anything
# else shares GPU0, drop to -ub 1024 (~1560 MiB) or -ub 256 (~2205 MiB); both cost only prefill.
# See OPTLOG attempts 165, 169 and 171.
# -ubd 64 is strictly faster than 256 (23.03 vs 21.43). -ctkd/-ctvd q4_0 put the draft KV cache
# at 151 MB instead of 537 and cost nothing measurable: acceptance 0.58170 vs 0.58361 for f16.
# See OPTLOG attempts 126, 143, 158 and 163.
#
# -b 32768 IS LOAD-BEARING FOR MTP, and is the whole reason long-context speculation works.
# With -b 262144 the entire prompt is one logical batch, and the MTP catch-up in
# common_speculative's process() then does a single ~5.3 GB memcpy over it. Changing only -b,
# same 259229-token prompt sent as ONE request:
#     -b 262144  ->  draft acceptance 0.00000, decode  5.41 t/s
#     -b  32768  ->  draft acceptance 0.98058, decode 26.13 t/s
# This was misdiagnosed for two sessions as a depth/VRAM/position problem. It is neither: a
# context taken to 259245 tokens incrementally holds 0.97403 acceptance at 27.49 t/s.
#
# GGML_CUDA_GRAPHS_PRE_VOLTA=0 goes with it. At -b 32768 and full context, CUDA graph
# instantiation is what exhausts VRAM (CUDA error out of memory at cudaGraphInstantiate),
# and turning graphs off costs 1.4% on tg256 -- 29.86 -> 29.44, inside the noise.
# See OPTLOG attempts 167 and 168.
BUILD="$(cd "$(dirname "$0")/../build" && pwd)"
MODEL="${QWEN_MODEL:-/mnt/fast/models/Qwen3.8-27B-Q6_K.gguf}"

[ -f "$MODEL" ] || { echo "qwen-server: model not found: $MODEL" >&2; exit 1; }

LD_LIBRARY_PATH="$BUILD${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" export LD_LIBRARY_PATH
: "${GGML_CUDA_P2P:=1}"              ; export GGML_CUDA_P2P
: "${GGML_CUDA_GRAPHS_PRE_VOLTA:=0}" ; export GGML_CUDA_GRAPHS_PRE_VOLTA

exec "$BUILD/llama-server" \
  -m "$MODEL" \
  -ngl 99 -sm tensor -fa 1 -ctk q4_0 -ctv q4_0 \
  -c 262144 -b 32768 -ub 2048 -np 1 \
  --spec-type draft-mtp --spec-draft-n-max 4 --spec-draft-p-min 0.2 \
  -ngld 99 -ubd 64 -ctkd q4_0 -ctvd q4_0 \
  --jinja --temp 0.3 --top-k 20 \
  --host 0.0.0.0 --port 8080 \
  --tools all \
  --mcp-servers-config "$HOME/mcp-servers.json" \
  "$@"
EOF
chmod +x "$BIN/qwen-server"

echo "    $n wrappers + qwen-server -> bin/"
