#!/usr/bin/env bash
# Generate bin/ wrappers for the release bundle so the binaries can go on PATH.
#
# Every binary in build/ carries a RUNPATH pointing at the machine it was compiled on, so run by
# absolute path it can silently load the wrong libggml-cuda.so. Each wrapper sets LD_LIBRARY_PATH
# to its own bundle first, then execs. That is the whole reason this directory exists.
#
# Called by sync.sh. Usage: ./make-wrappers.sh [/mnt/fast/p100-llamacpp-release]
set -euo pipefail

REL="${1:-/mnt/fast/p100-llamacpp-release}"
BIN="$REL/bin"
[ -d "$REL/build" ] || { echo "no build/ in $REL"; exit 1; }

rm -rf "$BIN"
mkdir -p "$BIN"

n=0
for exe in "$REL"/build/*; do
    name="$(basename "$exe")"
    case "$name" in *.so|*.so.*|*.a|*.cmake|*.h) continue ;; esac
    [ -f "$exe" ] && [ -x "$exe" ] || continue
    cat > "$BIN/$name" <<EOF
#!/bin/sh
# Generated by release-sync/make-wrappers.sh -- do not edit; regenerate instead.
BUILD="\$(cd "\$(dirname "\$0")/../build" && pwd)"
LD_LIBRARY_PATH="\$BUILD\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}" export LD_LIBRARY_PATH
exec "\$BUILD/$name" "\$@"
EOF
    chmod +x "$BIN/$name"
    n=$((n+1))
done

# The tuned serving configuration as a single command. Anything passed on the command line is
# appended, and llama.cpp takes the last occurrence of a flag, so `qwen-server --port 9000`
# overrides the port below without editing this file.
cat > "$BIN/qwen-server" <<'EOF'
#!/bin/sh
# Generated by release-sync/make-wrappers.sh -- do not edit; regenerate instead.
#
# The tuned long-context + MTP serving configuration for 2x P100. See docs/QUICKSTART.md for
# what each flag does and why. Extra arguments are appended and win over the defaults here.
#
# Sized for VRAM margin, not for peak shallow prefill. The attention mask is n_kv x ubatch and
# n_kv is the USED cache, so the footprint grows as the context fills: at -ub 2048 a genuinely
# full 262144 prompt dies 57 s into prefill and starves anything else on GPU0. -ub 512 costs
# shallow prefill (411 -> 380 t/s) and is within noise at depth (23.02 vs 22.91). -ubd 64 is
# strictly faster than 256 (23.03 vs 21.43). -ctkd/-ctvd q4_0 put the draft KV cache at 151 MB
# instead of 537 for -2.2% decode. See OPTLOG attempts 126, 143 and 155.
BUILD="$(cd "$(dirname "$0")/../build" && pwd)"
MODEL="${QWEN_MODEL:-/mnt/fast/models/Qwen3.8-27B-Q6_K.gguf}"

[ -f "$MODEL" ] || { echo "qwen-server: model not found: $MODEL" >&2; exit 1; }

LD_LIBRARY_PATH="$BUILD${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" export LD_LIBRARY_PATH
: "${GGML_CUDA_P2P:=1}"              ; export GGML_CUDA_P2P
: "${GGML_CUDA_GRAPHS_PRE_VOLTA:=1}" ; export GGML_CUDA_GRAPHS_PRE_VOLTA

exec "$BUILD/llama-server" \
  -m "$MODEL" \
  -ngl 99 -sm tensor -fa 1 -ctk q4_0 -ctv q4_0 \
  -c 262144 -b 262144 -ub 512 -np 1 \
  --spec-type draft-mtp --spec-draft-n-max 4 --spec-draft-p-min 0.2 \
  -ngld 99 -ubd 64 \
  --jinja --temp 0.3 --top-k 20 \
  --host 0.0.0.0 --port 8080 \
  --tools all \
  --mcp-servers-config "$HOME/mcp-servers.json" \
  "$@"
EOF
chmod +x "$BIN/qwen-server"

echo "    $n wrappers + qwen-server -> bin/"
